export const siteCopyEn = {
  meta: {
    siteName: "Nova Group",
    description:
      "Nova Group of Companies employs people in India for companies abroad. Nova Workforce is the employer of record. Employees and admins sign in here.",
  },
  nav: {
    label: "Primary",
    menu: "Menu",
    close: "Close",
    skip: "Skip to content",
    about: "About",
    companies: "Companies",
    services: "Services",
    how: "How we work",
    pricing: "Pricing",
    who: "Who we work with",
    faq: "FAQ",
    contact: "Contact",
    login: "Portal login",
    careers: "Careers",
    privacy: "Privacy",
    verify: "Verify a document",
  },
  footer: {
    blurb:
      "Nova Workforce and Nova Qore. Employment in India for companies that want a real employee relationship, with salary slips issued through this portal.",
    rights: "Nova Group of Companies",
    explore: "Explore",
    portal: "Portals",
    employee: "Employee login",
    admin: "Admin login",
    contactLabel: "Email",
    email: "thenovaworkforce@gmail.com",
  },
  home: {
    metaTitle: "Nova Group of Companies",
    kicker: "Nova Group of Companies",
    title: "Employ people in India without opening a company.",
    lede: "Nova Workforce is the employer of record. You choose the person and manage the work. We run the employment contract, payroll, and statutory employment in India. Nova Qore is the other company in the group.",
    primary: "Talk to us",
    secondary: "Portal login",
    assurances: ["No Indian entity required to start", "You manage the work", "Payroll and payslips included"],
    splitTitle: "How the relationship is split",
    split: [
      { title: "You", body: "Choose the person, set the goals, and manage the week." },
      { title: "Nova Workforce", body: "Employ them in India: contract, payroll, payslips, and statutory employment." },
      { title: "The employee", body: "Is employed locally and signs in here for salary slips and documents." },
    ],
    companiesTitle: "The group",
    companiesLede: "Two companies. One place for employees and operators to sign in.",
    servicesTitle: "What we take on",
    servicesLede: "The employment layer, so your team can stay on the work.",
    processTitle: "From first call to payday",
    processLede: "A short conversation, a quoted cost, then employment.",
    whoTitle: "Who this is for",
    compareTitle: "Three ways to have someone in India",
    compareLede: "The right structure depends on how the person will work.",
    compareColumns: ["", "Contractor", "Your Indian company", "Nova Workforce"],
    compareRows: [
      { label: "Legal employer", cells: ["The individual", "Your company", "Nova Workforce"] },
      { label: "Company in India", cells: ["Not required", "Required", "Not required"] },
      { label: "You direct the work", cells: ["A poor fit if the role is ongoing", "Yes", "Yes"] },
      { label: "Payroll and payslips", cells: ["Arranged separately", "Your team", "Included"] },
      { label: "Fits best when", cells: ["The work is truly independent", "You are ready to operate an entity", "The role is ongoing and you are not opening an entity yet"] },
    ],
    faqTitle: "Questions we answer on the call",
    ctaTitle: "Tell us the role. We will tell you the employment path and the cost.",
    ctaBody: "The first conversation is a working call. If employer-of-record employment is the wrong structure, we say so.",
    ctaAction: "Book a conversation",
  },
  about: {
    metaTitle: "About",
    kicker: "About",
    title: "Nova Group is Nova Workforce and Nova Qore.",
    lede: "We employ people in India for companies abroad, and we give those employees and our operators one portal for salary slips and documents.",
    points: [
      { title: "Nova Workforce", body: "Employer of record, based in Ahmedabad. We are the legal employer in India for people who work with your team." },
      { title: "Nova Qore", body: "A Nova Group company. People employed with Nova Qore use this same portal for salary slips and employment documents." },
      { title: "This website", body: "The public face of the group, and the sign-in door for employees, administrators, and other authorised users." },
    ],
    ctaTitle: "Ask which company should employ the person.",
    ctaBody: "We confirm the company, the cost, and the start path before anyone is hired.",
    ctaAction: "Contact Nova Group",
  },
  companies: {
    metaTitle: "Companies",
    kicker: "Companies",
    title: "The companies in the group.",
    lede: "Each company employs its own people. Employees sign in with the company that pays them.",
    items: [
      {
        id: "nova-workforce",
        name: "Nova Workforce",
        role: "Employer of record",
        place: "Ahmedabad, India",
        body: "Nova Workforce employs people in India on behalf of companies that do not want to open a local entity first. We handle the employment contract, onboarding, payroll, payslips, and the statutory side of that employment. You manage the person’s work.",
        points: ["Legal employer in India", "Payroll and salary slips", "Built for companies hiring from abroad"],
      },
      {
        id: "nova-qore",
        name: "Nova Qore",
        role: "Group company",
        place: "India",
        body: "Nova Qore is part of Nova Group. People employed with Nova Qore receive salary slips and employment documents through this portal, on the same sign-in path as Nova Workforce employees.",
        points: ["Employs its own people", "Salary slips in this portal", "Separate from Nova Workforce on the payroll records"],
      },
    ],
    ctaTitle: "Not sure which company fits the hire?",
    ctaBody: "Describe the role and where you operate. We will tell you which company employs the person.",
    ctaAction: "Talk to us",
  },
  services: {
    metaTitle: "Services",
    kicker: "Services",
    title: "Employment in India, handled.",
    lede: "We take the employer’s obligations. You keep the working relationship.",
    items: [
      { title: "Employer of record", body: "Nova Workforce is the legal employer in India. The person is your teammate in the work, and our employee on the contract." },
      { title: "Contracts and onboarding", body: "We issue the employment contract and complete the joining steps required for that employment." },
      { title: "Payroll", body: "Monthly pay is run under the employing company, with a salary slip the employee can download." },
      { title: "Statutory employment", body: "Professional tax, provident fund, and tax deducted at source are handled where they apply to that employment." },
      { title: "Employee documents", body: "Issued slips and employment documents stay in this portal. A public code can confirm that a document was issued, without showing salary or bank details." },
      { title: "Operator tools", body: "Administrators and other authorised users run companies, payroll, and documents from the same site." },
    ],
    ctaTitle: "Tell us the role you want to employ.",
    ctaBody: "We will say whether employer-of-record employment fits, and what it costs before you commit.",
    ctaAction: "Start with a call",
  },
  how: {
    metaTitle: "How we work",
    kicker: "How we work",
    title: "Four steps. You stay in charge of the work.",
    lede: "We do not hire the person for you. We employ the person you have chosen, in India, under Nova Workforce.",
    steps: [
      { title: "The call", body: "You describe the role, the country you operate from, and whether you already have a company in India." },
      { title: "The structure and the cost", body: "We confirm whether employer-of-record employment is the right path, and we quote the monthly cost before anyone is hired." },
      { title: "Contract and joining", body: "Nova Workforce issues the employment contract and completes onboarding. You agree the start date with the person." },
      { title: "Payroll each month", body: "We run pay. The employee signs in here for slips and documents. You keep managing the work." },
    ],
    needTitle: "What we need from you",
    need: [
      "The role and how you will manage the person",
      "Where your company operates",
      "The salary you intend to pay",
      "The date you want employment to start",
    ],
    ctaTitle: "Bring the role. Leave with a structure and a number.",
    ctaBody: "If we cannot employ the person cleanly, we tell you on the call.",
    ctaAction: "Book the call",
  },
  pricing: {
    metaTitle: "Pricing",
    kicker: "Pricing",
    title: "You see the monthly cost before you hire.",
    lede: "There is no fee to have the conversation. You pay when Nova Workforce employs the person.",
    cards: [
      { title: "The conversation", body: "A working call about the role, the employment structure, and whether we can take it. No charge." },
      { title: "The employment cost", body: "Salary and the statutory costs that apply in India, plus Nova Workforce’s service fee. We quote the monthly figure for that role before you commit." },
      { title: "What the fee covers", body: "The employment contract, onboarding, monthly payroll, salary slips, and the statutory handling that belongs to that employment." },
    ],
    note: "We do not publish a flat rate. The number depends on salary, location, and the statutory costs for that person. You receive it before an offer goes out.",
    ctaTitle: "Ask for a number for a specific role.",
    ctaBody: "Tell us the salary band and the country you work from. We reply with the employment path and the monthly cost.",
    ctaAction: "Request a quote",
  },
  who: {
    metaTitle: "Who we work with",
    kicker: "Who we work with",
    title: "Companies that want an employee in India.",
    lede: "The usual starting point is a company abroad hiring someone who will be managed like the rest of the team.",
    items: [
      { title: "First hire in India", body: "You want one person on the ground and you are not ready to open an Indian company for that seat." },
      { title: "An ongoing role", body: "You will direct the work. A contractor arrangement would be the wrong employment structure." },
      { title: "Teams already in the group", body: "People employed by Nova Workforce or Nova Qore, and the administrators who run those companies, already sign in here." },
    ],
    ctaTitle: "If the person will be managed by your team, start here.",
    ctaBody: "We will tell you if employer-of-record employment is the right structure for that role.",
    ctaAction: "Describe the role",
  },
  faq: {
    metaTitle: "FAQ",
    kicker: "FAQ",
    title: "Questions we get before the first hire.",
    lede: "Straight answers. The call is where we apply them to your role.",
    items: [
      { q: "Do I need a company in India?", a: "No, not to start. Nova Workforce can be the employer in India. If you already have an entity, tell us on the call and we will say which path fits." },
      { q: "Who is the legal employer?", a: "Nova Workforce, when we are the employer of record. The person works with your team. The employment contract is with Nova Workforce." },
      { q: "How is this different from hiring a contractor?", a: "A contractor is an independent business. Employer-of-record employment is for a person you manage as part of your team. We use it when the role is ongoing employment." },
      { q: "Who manages the day-to-day work?", a: "You do. We do not supervise their tasks. We run the employment." },
      { q: "Can they work our hours?", a: "Yes, when they agree to that schedule. Confirm the hours and the holiday calendar before the offer." },
      { q: "What do employees use this website for?", a: "Employees sign in to download salary slips and employment documents. Administrators and other authorised users run payroll and company records." },
      { q: "Who can sign in?", a: "Employees use the employee portal. Super admins, operations managers, and other users with a grant use the admin portal. There is no public account signup." },
      { q: "What is Nova Qore?", a: "Nova Qore is a company in Nova Group. People it employs use this portal for salary slips and documents. It is a separate employer from Nova Workforce." },
      { q: "When do I pay?", a: "You pay when we employ the person. The conversation and the quote come first. The monthly cost is confirmed before you commit." },
      { q: "How is a salary slip checked?", a: "Each issued document can be verified with its code. The public check shows that the document is valid. It does not show salary or bank details." },
    ],
    ctaTitle: "Still deciding?",
    ctaBody: "Send the role. We will answer with the structure and the cost.",
    ctaAction: "Contact us",
  },
  contact: {
    metaTitle: "Contact",
    kicker: "Contact",
    title: "Tell us who you want to employ.",
    lede: "We reply within one business day. The first call is about the role, the cost, and whether we can employ the person.",
    emailLabel: "Email",
    email: "thenovaworkforce@gmail.com",
    emailNote: "Prefer to write directly? Use the address. The form reaches the same inbox.",
    form: {
      name: "Your name",
      email: "Work email",
      organisation: "Company",
      phone: "Phone",
      optional: "Optional",
      topic: "What is this about?",
      topics: [
        { value: "eor", label: "Employing someone in India" },
        { value: "payroll", label: "Payroll or a document" },
        { value: "careers", label: "Working with Nova Group" },
        { value: "other", label: "Something else" },
      ],
      message: "Message",
      messageHint: "Role, country you operate from, and the salary you have in mind.",
      submit: "Send",
      sending: "Sending…",
      success: "Received. We will reply to the email you entered.",
      error: "We could not send that. Write to us at the address on this page.",
      invalid: "Check the highlighted fields and try again.",
    },
  },
  careers: {
    metaTitle: "Careers",
    kicker: "Careers",
    title: "Already employed with us? Sign in.",
    lede: "Nova Workforce and Nova Qore employees use the employee portal for salary slips and documents. We do not list open roles on this site.",
    cards: [
      { title: "Employees", body: "Sign in with your employee ID or registered mobile number.", action: "Employee login", href: "/login/employee" },
      { title: "Administrators and other users", body: "Super admins, operations managers, and other authorised users sign in through the admin portal.", action: "Admin login", href: "/login/admin" },
      { title: "Want to work with the group?", body: "Send a note through the contact form. Tell us the work you do and where you are based.", action: "Contact", href: "/contact" },
    ],
  },
  privacy: {
    metaTitle: "Privacy",
    kicker: "Privacy",
    title: "How this site handles personal information.",
    lede: "The public pages and the employee portal are different places, with different data.",
    sections: [
      { title: "Who we are", body: "This site is operated for Nova Group of Companies, covering Nova Workforce and Nova Qore. Privacy questions go to thenovaworkforce@gmail.com." },
      { title: "Public pages", body: "Reading the public pages does not require an account. We do not ask you to create one." },
      { title: "Contact form", body: "If you write to us, we receive your name, email, company, phone if you gave one, the topic, and the message. We use that to reply. We do not sell it." },
      { title: "Employee and admin portal", body: "Salary slips, bank details, and employment records are available only to the employee they belong to and to authorised operators of that company. The public document check confirms a document is valid and does not show salary or bank details." },
      { title: "How long we keep a message", body: "Contact messages are emailed to the group inbox. Keep a copy of anything you need for your own records." },
      { title: "Ask us", body: "To ask about your information, email thenovaworkforce@gmail.com from the address you used." },
    ],
  },
};

export type SiteCopy = typeof siteCopyEn;
