import type { SiteCopy } from "./en";

export const siteCopyEs: SiteCopy = {
  meta: {
    siteName: "Grupo Nova",
    description:
      "El Grupo Nova emplea personas en India para empresas en el extranjero. Nova Workforce es el empleador registrado. Empleados y administradores entran aquí.",
  },
  nav: {
    label: "Principal",
    menu: "Menú",
    close: "Cerrar",
    skip: "Saltar al contenido",
    about: "Nosotros",
    companies: "Empresas",
    services: "Servicios",
    how: "Cómo trabajamos",
    pricing: "Precios",
    who: "Con quién",
    faq: "FAQ",
    contact: "Contacto",
    login: "Acceso al portal",
    careers: "Empleo",
    privacy: "Privacidad",
    verify: "Verificar un documento",
  },
  footer: {
    blurb:
      "Nova Workforce y Nova Qore. Empleo en India para empresas que quieren una relación laboral real, con recibos emitidos en este portal.",
    rights: "Grupo Nova",
    explore: "Explorar",
    portal: "Portales",
    employee: "Acceso empleado",
    admin: "Acceso admin",
    contactLabel: "Correo",
    email: "thenovaworkforce@gmail.com",
  },
  home: {
    metaTitle: "Grupo Nova",
    kicker: "Grupo Nova",
    title: "Emplee personas en India sin abrir una empresa.",
    lede: "Nova Workforce es el empleador registrado. Usted elige a la persona y dirige el trabajo. Nosotros llevamos el contrato, la nómina y las obligaciones laborales en India. Nova Qore es la otra empresa del grupo.",
    primary: "Escríbanos",
    secondary: "Acceso al portal",
    assurances: ["No hace falta una empresa en India para empezar", "Usted dirige el trabajo", "Nómina y recibos incluidos"],
    splitTitle: "Cómo se reparte la relación",
    split: [
      { title: "Usted", body: "Elige a la persona, fija los objetivos y dirige la semana." },
      { title: "Nova Workforce", body: "La emplea en India: contrato, nómina, recibos y obligaciones legales." },
      { title: "La persona empleada", body: "Está empleada en el país y entra aquí para sus recibos y documentos." },
    ],
    companiesTitle: "El grupo",
    companiesLede: "Dos empresas. Un solo lugar para que empleados y operadores inicien sesión.",
    servicesTitle: "Lo que asumimos",
    servicesLede: "La capa de empleador, para que su equipo siga en el trabajo.",
    processTitle: "De la llamada al pago",
    processLede: "Una conversación breve, un coste indicado y después el empleo.",
    whoTitle: "Para quién es",
    compareTitle: "Tres formas de tener a alguien en India",
    compareLede: "La estructura correcta depende de cómo trabajará la persona.",
    compareColumns: ["", "Contratista", "Su empresa en India", "Nova Workforce"],
    compareRows: [
      { label: "Empleador legal", cells: ["La persona", "Su empresa", "Nova Workforce"] },
      { label: "Empresa en India", cells: ["No hace falta", "Hace falta", "No hace falta"] },
      { label: "Usted dirige el trabajo", cells: ["Mal encaje si el puesto es continuo", "Sí", "Sí"] },
      { label: "Nómina y recibos", cells: ["Se organizan aparte", "Su equipo", "Incluidos"] },
      { label: "Encaja mejor cuando", cells: ["El trabajo es realmente independiente", "Está listo para operar una empresa", "El puesto es continuo y aún no abre una empresa"] },
    ],
    faqTitle: "Preguntas que resolvemos en la llamada",
    ctaTitle: "Cuéntenos el puesto. Le diremos la vía de empleo y el coste.",
    ctaBody: "La primera conversación es una llamada de trabajo. Si el empleador registrado no es la estructura correcta, lo decimos.",
    ctaAction: "Pedir una llamada",
  },
  about: {
    metaTitle: "Nosotros",
    kicker: "Nosotros",
    title: "El Grupo Nova es Nova Workforce y Nova Qore.",
    lede: "Empleamos personas en India para empresas en el extranjero, y damos a esos empleados y a nuestros operadores un portal para recibos y documentos.",
    points: [
      { title: "Nova Workforce", body: "Empleador registrado, con sede en Ahmedabad. Somos el empleador legal en India de las personas que trabajan con su equipo." },
      { title: "Nova Qore", body: "Empresa del Grupo Nova. Quienes emplea Nova Qore usan este mismo portal para recibos y documentos de empleo." },
      { title: "Este sitio", body: "La cara pública del grupo y la puerta de acceso de empleados, administradores y otros usuarios autorizados." },
    ],
    ctaTitle: "Pregunte qué empresa debe emplear a la persona.",
    ctaBody: "Confirmamos la empresa, el coste y el inicio antes de contratar.",
    ctaAction: "Contactar al Grupo Nova",
  },
  companies: {
    metaTitle: "Empresas",
    kicker: "Empresas",
    title: "Las empresas del grupo.",
    lede: "Cada empresa emplea a su propia gente. El empleado entra con la empresa que le paga.",
    items: [
      {
        id: "nova-workforce",
        name: "Nova Workforce",
        role: "Empleador registrado",
        place: "Ahmedabad, India",
        body: "Nova Workforce emplea personas en India para empresas que no quieren abrir primero una entidad local. Llevamos el contrato, la incorporación, la nómina, los recibos y el lado legal de ese empleo. Usted dirige el trabajo.",
        points: ["Empleador legal en India", "Nómina y recibos", "Pensado para empresas que contratan desde el extranjero"],
      },
      {
        id: "nova-qore",
        name: "Nova Qore",
        role: "Empresa del grupo",
        place: "India",
        body: "Nova Qore forma parte del Grupo Nova. Las personas que emplea reciben recibos y documentos de empleo en este portal, por el mismo acceso que los empleados de Nova Workforce.",
        points: ["Emplea a su propia gente", "Recibos en este portal", "Empleador distinto de Nova Workforce en los registros de nómina"],
      },
    ],
    ctaTitle: "¿No sabe qué empresa encaja?",
    ctaBody: "Describa el puesto y desde dónde opera. Le diremos qué empresa emplea a la persona.",
    ctaAction: "Escríbanos",
  },
  services: {
    metaTitle: "Servicios",
    kicker: "Servicios",
    title: "El empleo en India, resuelto.",
    lede: "Asumimos las obligaciones del empleador. Usted conserva la relación de trabajo.",
    items: [
      { title: "Empleador registrado", body: "Nova Workforce es el empleador legal en India. La persona es de su equipo en el trabajo, y nuestra empleada en el contrato." },
      { title: "Contratos e incorporación", body: "Emitimos el contrato de trabajo y completamos los pasos de alta de ese empleo." },
      { title: "Nómina", body: "El pago mensual corre a cargo de la empresa empleadora, con un recibo que el empleado descarga." },
      { title: "Obligaciones legales", body: "El impuesto profesional, el provident fund y la retención fiscal se atienden cuando aplican a ese empleo." },
      { title: "Documentos del empleado", body: "Los recibos emitidos y los documentos de empleo permanecen en este portal. Un código público confirma que un documento se emitió, sin mostrar salario ni datos bancarios." },
      { title: "Herramientas de operación", body: "Los administradores y otros usuarios autorizados gestionan empresas, nómina y documentos desde el mismo sitio." },
    ],
    ctaTitle: "Cuéntenos el puesto que quiere emplear.",
    ctaBody: "Diremos si el empleador registrado encaja, y cuánto cuesta antes de que se comprometa.",
    ctaAction: "Empezar con una llamada",
  },
  how: {
    metaTitle: "Cómo trabajamos",
    kicker: "Cómo trabajamos",
    title: "Cuatro pasos. Usted sigue al mando del trabajo.",
    lede: "No elegimos a la persona por usted. Empleamos en India, bajo Nova Workforce, a la persona que usted eligió.",
    steps: [
      { title: "La llamada", body: "Describe el puesto, el país desde el que opera y si ya tiene una empresa en India." },
      { title: "La estructura y el coste", body: "Confirmamos si el empleador registrado es el camino correcto y cotizamos el coste mensual antes de contratar." },
      { title: "Contrato e ingreso", body: "Nova Workforce emite el contrato y completa la incorporación. Usted acuerda la fecha de inicio con la persona." },
      { title: "La nómina cada mes", body: "Pagamos el salario. El empleado entra aquí para recibos y documentos. Usted sigue dirigiendo el trabajo." },
    ],
    needTitle: "Lo que necesitamos de usted",
    need: [
      "El puesto y cómo dirigirá a la persona",
      "El país donde opera su empresa",
      "El salario que piensa pagar",
      "La fecha en que quiere iniciar el empleo",
    ],
    ctaTitle: "Traiga el puesto. Salga con una estructura y una cifra.",
    ctaBody: "Si no podemos emplear a la persona con claridad, se lo decimos en la llamada.",
    ctaAction: "Reservar la llamada",
  },
  pricing: {
    metaTitle: "Precios",
    kicker: "Precios",
    title: "Ve el coste mensual antes de contratar.",
    lede: "La conversación no se cobra. Paga cuando Nova Workforce emplea a la persona.",
    cards: [
      { title: "La conversación", body: "Una llamada sobre el puesto, la estructura de empleo y si podemos asumirlo. Sin cargo." },
      { title: "El coste de empleo", body: "El salario y las cargas legales que apliquen en India, más el honorario de Nova Workforce. Cotizamos la cifra mensual de ese puesto antes de que se comprometa." },
      { title: "Lo que cubre el honorario", body: "El contrato, la incorporación, la nómina mensual, los recibos y el tratamiento legal de ese empleo." },
    ],
    note: "No publicamos una tarifa única. La cifra depende del salario, el lugar y las cargas de esa persona. La recibe antes de la oferta.",
    ctaTitle: "Pida una cifra para un puesto concreto.",
    ctaBody: "Indique la banda salarial y el país desde el que trabaja. Respondemos con la vía de empleo y el coste mensual.",
    ctaAction: "Pedir una cotización",
  },
  who: {
    metaTitle: "Con quién",
    kicker: "Con quién trabajamos",
    title: "Empresas que quieren un empleado en India.",
    lede: "El punto de partida habitual es una empresa en el extranjero que contrata a alguien dirigido como el resto del equipo.",
    items: [
      { title: "Primera contratación en India", body: "Quiere una persona en el terreno y no está listo para abrir una empresa india para ese puesto." },
      { title: "Un puesto continuo", body: "Usted dirigirá el trabajo. Un arreglo de contratista sería la estructura equivocada." },
      { title: "Equipos que ya están en el grupo", body: "Las personas empleadas por Nova Workforce o Nova Qore, y los administradores de esas empresas, ya entran aquí." },
    ],
    ctaTitle: "Si su equipo dirigirá a la persona, empiece aquí.",
    ctaBody: "Le diremos si el empleador registrado es la estructura correcta para ese puesto.",
    ctaAction: "Describir el puesto",
  },
  faq: {
    metaTitle: "FAQ",
    kicker: "FAQ",
    title: "Preguntas antes de la primera contratación.",
    lede: "Respuestas directas. La llamada sirve para aplicarlas a su puesto.",
    items: [
      { q: "¿Necesito una empresa en India?", a: "No, para empezar. Nova Workforce puede ser el empleador en India. Si ya tiene una entidad, dígalo en la llamada." },
      { q: "¿Quién es el empleador legal?", a: "Nova Workforce, cuando somos el empleador registrado. La persona trabaja con su equipo. El contrato es con Nova Workforce." },
      { q: "¿En qué se diferencia de un contratista?", a: "Un contratista es un negocio independiente. El empleador registrado es para una persona que usted dirige como parte de su equipo, en un empleo continuo." },
      { q: "¿Quién dirige el trabajo diario?", a: "Usted. No supervisamos sus tareas. Llevamos el empleo." },
      { q: "¿Puede trabajar en nuestro horario?", a: "Sí, si acepta ese horario. Confirme las horas y el calendario de festivos antes de la oferta." },
      { q: "¿Para qué usan los empleados este sitio?", a: "Los empleados entran para descargar recibos y documentos. Los administradores y otros usuarios autorizados gestionan la nómina y los expedientes." },
      { q: "¿Quién puede entrar?", a: "Los empleados usan el portal de empleados. Los superadmins, los responsables de operaciones y otros usuarios con permiso usan el portal de administración. No hay registro público." },
      { q: "¿Qué es Nova Qore?", a: "Nova Qore es una empresa del Grupo Nova. Las personas que emplea usan este portal para recibos y documentos. Es un empleador distinto de Nova Workforce." },
      { q: "¿Cuándo pago?", a: "Paga cuando empleamos a la persona. Primero van la conversación y la cotización. El coste mensual se confirma antes de que se comprometa." },
      { q: "¿Cómo se comprueba un recibo?", a: "Cada documento emitido se puede verificar con su código. La comprobación pública confirma que el documento es válido. No muestra salario ni datos bancarios." },
    ],
    ctaTitle: "¿Aún lo está decidiendo?",
    ctaBody: "Envíe el puesto. Responderemos con la estructura y el coste.",
    ctaAction: "Contactarnos",
  },
  contact: {
    metaTitle: "Contacto",
    kicker: "Contacto",
    title: "Díganos a quién quiere emplear.",
    lede: "Respondemos en un día laborable. La primera llamada trata del puesto, el coste y si podemos emplear a la persona.",
    emailLabel: "Correo",
    email: "thenovaworkforce@gmail.com",
    emailNote: "¿Prefiere escribir directo? Use la dirección. El formulario llega al mismo buzón.",
    form: {
      name: "Su nombre",
      email: "Correo de trabajo",
      organisation: "Empresa",
      phone: "Teléfono",
      optional: "Opcional",
      topic: "Tema",
      topics: [
        { value: "eor", label: "Emplear a alguien en India" },
        { value: "payroll", label: "Nómina o un documento" },
        { value: "careers", label: "Trabajar con el Grupo Nova" },
        { value: "other", label: "Otro tema" },
      ],
      message: "Mensaje",
      messageHint: "El puesto, el país desde el que opera y el salario que tiene en mente.",
      submit: "Enviar",
      sending: "Enviando…",
      success: "Recibido. Responderemos al correo que indicó.",
      error: "No pudimos enviarlo. Escríbanos a la dirección de esta página.",
      invalid: "Revise los campos marcados e inténtelo de nuevo.",
    },
  },
  careers: {
    metaTitle: "Empleo",
    kicker: "Empleo",
    title: "¿Ya trabaja con nosotros? Entre.",
    lede: "Los empleados de Nova Workforce y Nova Qore usan el portal de empleados para recibos y documentos. No publicamos vacantes en este sitio.",
    cards: [
      { title: "Empleados", body: "Entre con su ID de empleado o el móvil registrado.", action: "Acceso empleado", href: "/login/employee" },
      { title: "Administradores y otros usuarios", body: "Los superadmins, los responsables de operaciones y otros usuarios autorizados entran por el portal de administración.", action: "Acceso admin", href: "/login/admin" },
      { title: "¿Quiere trabajar con el grupo?", body: "Envíe una nota por el formulario. Cuéntenos su oficio y dónde está.", action: "Contacto", href: "/contact" },
    ],
  },
  privacy: {
    metaTitle: "Privacidad",
    kicker: "Privacidad",
    title: "Cómo trata este sitio la información personal.",
    lede: "Las páginas públicas y el portal de empleados son espacios distintos, con datos distintos.",
    sections: [
      { title: "Quiénes somos", body: "Este sitio se opera para el Grupo Nova, que cubre Nova Workforce y Nova Qore. Las preguntas de privacidad van a thenovaworkforce@gmail.com." },
      { title: "Páginas públicas", body: "Leer las páginas públicas no exige una cuenta. No pedimos que cree una." },
      { title: "Formulario de contacto", body: "Si nos escribe, recibimos su nombre, correo, empresa, teléfono si lo dio, el tema y el mensaje. Lo usamos para responder. No lo vendemos." },
      { title: "Portal de empleados y admin", body: "Los recibos, los datos bancarios y los expedientes de empleo solo están disponibles para el empleado al que pertenecen y para los operadores autorizados de esa empresa. La verificación pública confirma que un documento es válido y no muestra salario ni datos bancarios." },
      { title: "Cuánto guardamos un mensaje", body: "Los mensajes de contacto se envían por correo al buzón del grupo. Guarde una copia de lo que necesite." },
      { title: "Pregúntenos", body: "Para consultar sus datos, escriba a thenovaworkforce@gmail.com desde la dirección que utilizó." },
    ],
  },
};
