import type { SiteCopy } from "./en";

export const siteCopyFr: SiteCopy = {
  meta: {
    siteName: "Groupe Nova",
    description:
      "Le groupe Nova emploie des personnes en Inde pour des sociétés à l’étranger. Nova Workforce est l’employeur enregistré. Employés et administrateurs se connectent ici.",
  },
  nav: {
    label: "Principal",
    menu: "Menu",
    close: "Fermer",
    skip: "Aller au contenu",
    about: "À propos",
    companies: "Sociétés",
    services: "Services",
    how: "Notre méthode",
    pricing: "Tarifs",
    who: "Avec qui",
    faq: "FAQ",
    contact: "Contact",
    login: "Accès portail",
    careers: "Carrières",
    privacy: "Confidentialité",
    verify: "Vérifier un document",
  },
  footer: {
    blurb:
      "Nova Workforce et Nova Qore. L’emploi en Inde pour les sociétés qui veulent une vraie relation de travail, avec les bulletins émis dans ce portail.",
    rights: "Groupe Nova",
    explore: "Explorer",
    portal: "Portails",
    employee: "Connexion employé",
    admin: "Connexion admin",
    contactLabel: "E-mail",
    email: "thenovaworkforce@gmail.com",
  },
  home: {
    metaTitle: "Groupe Nova",
    kicker: "Groupe Nova",
    title: "Employer en Inde sans créer de société.",
    lede: "Nova Workforce est l’employeur enregistré. Vous choisissez la personne et dirigez le travail. Nous gérons le contrat, la paie et les obligations d’emploi en Inde. Nova Qore est l’autre société du groupe.",
    primary: "Nous écrire",
    secondary: "Accès portail",
    assurances: ["Pas de société indienne pour commencer", "Vous dirigez le travail", "Paie et bulletins inclus"],
    splitTitle: "Comment la relation se répartit",
    split: [
      { title: "Vous", body: "Vous choisissez la personne, fixez les objectifs et suivez la semaine." },
      { title: "Nova Workforce", body: "Nous l’employons en Inde : contrat, paie, bulletins et obligations légales." },
      { title: "La personne employée", body: "Elle est employée localement et se connecte ici pour ses bulletins et documents." },
    ],
    companiesTitle: "Le groupe",
    companiesLede: "Deux sociétés. Un seul endroit pour la connexion des employés et des opérateurs.",
    servicesTitle: "Ce que nous prenons en charge",
    servicesLede: "La couche employeur, pour que votre équipe reste sur le travail.",
    processTitle: "De l’appel au salaire",
    processLede: "Une conversation courte, un coût annoncé, puis l’emploi.",
    whoTitle: "Pour qui",
    compareTitle: "Trois façons d’avoir quelqu’un en Inde",
    compareLede: "La bonne structure dépend de la façon dont la personne travaillera.",
    compareColumns: ["", "Prestataire", "Votre société indienne", "Nova Workforce"],
    compareRows: [
      { label: "Employeur légal", cells: ["La personne", "Votre société", "Nova Workforce"] },
      { label: "Société en Inde", cells: ["Pas nécessaire", "Nécessaire", "Pas nécessaire"] },
      { label: "Vous dirigez le travail", cells: ["Mauvais cadre si le rôle est continu", "Oui", "Oui"] },
      { label: "Paie et bulletins", cells: ["À organiser à part", "Votre équipe", "Inclus"] },
      { label: "Convient surtout quand", cells: ["Le travail est vraiment indépendant", "Vous êtes prêt à exploiter une société", "Le rôle est continu et vous n’ouvrez pas encore de société"] },
    ],
    faqTitle: "Questions que nous traitons à l’appel",
    ctaTitle: "Décrivez le rôle. Nous dirons le cadre d’emploi et le coût.",
    ctaBody: "Le premier échange est un appel de travail. Si l’employeur enregistré n’est pas le bon cadre, nous le disons.",
    ctaAction: "Demander un appel",
  },
  about: {
    metaTitle: "À propos",
    kicker: "À propos",
    title: "Le groupe Nova, c’est Nova Workforce et Nova Qore.",
    lede: "Nous employons des personnes en Inde pour des sociétés à l’étranger, et nous donnons à ces employés et à nos opérateurs un portail pour les bulletins et les documents.",
    points: [
      { title: "Nova Workforce", body: "Employeur enregistré, basé à Ahmedabad. Nous sommes l’employeur légal en Inde pour les personnes qui travaillent avec votre équipe." },
      { title: "Nova Qore", body: "Société du groupe Nova. Les personnes employées par Nova Qore utilisent ce même portail pour les bulletins et les documents d’emploi." },
      { title: "Ce site", body: "La vitrine du groupe, et la porte de connexion des employés, des administrateurs et des autres utilisateurs autorisés." },
    ],
    ctaTitle: "Demandez quelle société doit employer la personne.",
    ctaBody: "Nous confirmons la société, le coût et le démarrage avant toute embauche.",
    ctaAction: "Contacter le groupe Nova",
  },
  companies: {
    metaTitle: "Sociétés",
    kicker: "Sociétés",
    title: "Les sociétés du groupe.",
    lede: "Chaque société emploie ses propres personnes. L’employé se connecte avec la société qui le paie.",
    items: [
      {
        id: "nova-workforce",
        name: "Nova Workforce",
        role: "Employeur enregistré",
        place: "Ahmedabad, Inde",
        body: "Nova Workforce emploie des personnes en Inde pour le compte de sociétés qui ne veulent pas ouvrir d’abord une entité locale. Nous gérons le contrat, l’intégration, la paie, les bulletins et le volet légal de cet emploi. Vous dirigez le travail.",
        points: ["Employeur légal en Inde", "Paie et bulletins", "Conçu pour les sociétés qui recrutent depuis l’étranger"],
      },
      {
        id: "nova-qore",
        name: "Nova Qore",
        role: "Société du groupe",
        place: "Inde",
        body: "Nova Qore fait partie du groupe Nova. Les personnes qu’elle emploie reçoivent bulletins et documents d’emploi dans ce portail, sur le même chemin de connexion que les employés de Nova Workforce.",
        points: ["Emploie ses propres personnes", "Bulletins dans ce portail", "Employeur distinct de Nova Workforce dans les registres de paie"],
      },
    ],
    ctaTitle: "Vous ne savez pas quelle société convient ?",
    ctaBody: "Décrivez le rôle et le pays d’où vous opérez. Nous dirons quelle société emploie la personne.",
    ctaAction: "Nous écrire",
  },
  services: {
    metaTitle: "Services",
    kicker: "Services",
    title: "L’emploi en Inde, pris en charge.",
    lede: "Nous portons les obligations de l’employeur. Vous gardez la relation de travail.",
    items: [
      { title: "Employeur enregistré", body: "Nova Workforce est l’employeur légal en Inde. La personne est dans votre équipe pour le travail, et notre employée sur le contrat." },
      { title: "Contrats et intégration", body: "Nous établissons le contrat de travail et les étapes d’entrée liées à cet emploi." },
      { title: "Paie", body: "La paie mensuelle est faite par la société employeuse, avec un bulletin que l’employé télécharge." },
      { title: "Obligations légales", body: "Taxe professionnelle, provident fund et retenue à la source sont traités lorsqu’ils s’appliquent à cet emploi." },
      { title: "Documents des employés", body: "Les bulletins émis et les documents d’emploi restent dans ce portail. Un code public confirme qu’un document a été émis, sans afficher le salaire ni les coordonnées bancaires." },
      { title: "Outils des opérateurs", body: "Les administrateurs et les autres utilisateurs autorisés gèrent sociétés, paie et documents depuis le même site." },
    ],
    ctaTitle: "Dites-nous le rôle à employer.",
    ctaBody: "Nous dirons si l’employeur enregistré convient, et ce que cela coûte avant votre engagement.",
    ctaAction: "Commencer par un appel",
  },
  how: {
    metaTitle: "Notre méthode",
    kicker: "Notre méthode",
    title: "Quatre étapes. Vous restez responsable du travail.",
    lede: "Nous ne choisissons pas la personne à votre place. Nous employons en Inde, sous Nova Workforce, la personne que vous avez choisie.",
    steps: [
      { title: "L’appel", body: "Vous décrivez le rôle, le pays d’où vous opérez, et si vous avez déjà une société en Inde." },
      { title: "Le cadre et le coût", body: "Nous confirmons si l’employeur enregistré est le bon chemin, et nous annonçons le coût mensuel avant toute embauche." },
      { title: "Contrat et entrée", body: "Nova Workforce émet le contrat et termine l’intégration. Vous convenez de la date de début avec la personne." },
      { title: "La paie chaque mois", body: "Nous versons le salaire. L’employé se connecte ici pour les bulletins et documents. Vous continuez à diriger le travail." },
    ],
    needTitle: "Ce qu’il nous faut de vous",
    need: [
      "Le rôle et la façon dont vous dirigerez la personne",
      "Le pays où votre société opère",
      "Le salaire que vous comptez verser",
      "La date de début souhaitée",
    ],
    ctaTitle: "Apportez le rôle. Repartez avec un cadre et un chiffre.",
    ctaBody: "Si nous ne pouvons pas employer la personne proprement, nous le disons à l’appel.",
    ctaAction: "Réserver l’appel",
  },
  pricing: {
    metaTitle: "Tarifs",
    kicker: "Tarifs",
    title: "Vous voyez le coût mensuel avant d’embaucher.",
    lede: "La conversation n’est pas facturée. Vous payez lorsque Nova Workforce emploie la personne.",
    cards: [
      { title: "La conversation", body: "Un appel sur le rôle, le cadre d’emploi et notre capacité à le prendre. Sans frais." },
      { title: "Le coût d’emploi", body: "Le salaire et les charges légales applicables en Inde, plus les honoraires de Nova Workforce. Nous annonçons le montant mensuel de ce rôle avant votre engagement." },
      { title: "Ce que les honoraires couvrent", body: "Le contrat, l’intégration, la paie mensuelle, les bulletins et le traitement légal qui appartient à cet emploi." },
    ],
    note: "Nous ne publions pas de forfait unique. Le chiffre dépend du salaire, du lieu et des charges de cette personne. Vous le recevez avant l’offre.",
    ctaTitle: "Demandez un chiffre pour un rôle précis.",
    ctaBody: "Indiquez la fourchette de salaire et le pays d’où vous travaillez. Nous répondons avec le cadre d’emploi et le coût mensuel.",
    ctaAction: "Demander un devis",
  },
  who: {
    metaTitle: "Avec qui",
    kicker: "Avec qui nous travaillons",
    title: "Des sociétés qui veulent un employé en Inde.",
    lede: "Le point de départ habituel est une société à l’étranger qui embauche une personne dirigée comme le reste de l’équipe.",
    items: [
      { title: "Premier recrutement en Inde", body: "Vous voulez une personne sur place et vous n’êtes pas prêt à ouvrir une société indienne pour ce poste." },
      { title: "Un rôle continu", body: "Vous dirigerez le travail. Un contrat de prestataire serait le mauvais cadre." },
      { title: "Équipes déjà dans le groupe", body: "Les personnes employées par Nova Workforce ou Nova Qore, et les administrateurs de ces sociétés, se connectent déjà ici." },
    ],
    ctaTitle: "Si votre équipe dirigera la personne, commencez ici.",
    ctaBody: "Nous dirons si l’employeur enregistré est le bon cadre pour ce rôle.",
    ctaAction: "Décrire le rôle",
  },
  faq: {
    metaTitle: "FAQ",
    kicker: "FAQ",
    title: "Questions avant le premier recrutement.",
    lede: "Des réponses directes. L’appel sert à les appliquer à votre rôle.",
    items: [
      { q: "Faut-il une société en Inde ?", a: "Non, pas pour commencer. Nova Workforce peut être l’employeur en Inde. Si vous avez déjà une entité, dites-le à l’appel." },
      { q: "Qui est l’employeur légal ?", a: "Nova Workforce, lorsque nous sommes l’employeur enregistré. La personne travaille avec votre équipe. Le contrat est avec Nova Workforce." },
      { q: "En quoi est-ce différent d’un prestataire ?", a: "Un prestataire est une activité indépendante. L’employeur enregistré concerne une personne que vous dirigez dans votre équipe, pour un emploi continu." },
      { q: "Qui dirige le travail au quotidien ?", a: "Vous. Nous ne supervisons pas les tâches. Nous gérons l’emploi." },
      { q: "La personne peut-elle travailler sur nos horaires ?", a: "Oui, si elle accepte ce rythme. Confirmez les horaires et le calendrier de congés avant l’offre." },
      { q: "À quoi sert ce site pour les employés ?", a: "Les employés se connectent pour télécharger bulletins et documents. Les administrateurs et autres utilisateurs autorisés gèrent la paie et les dossiers." },
      { q: "Qui peut se connecter ?", a: "Les employés utilisent le portail employé. Les super admins, les responsables des opérations et les autres utilisateurs autorisés utilisent le portail admin. Il n’y a pas d’inscription publique." },
      { q: "Qu’est-ce que Nova Qore ?", a: "Nova Qore est une société du groupe Nova. Les personnes qu’elle emploie utilisent ce portail pour les bulletins et documents. C’est un employeur distinct de Nova Workforce." },
      { q: "Quand est-ce que je paie ?", a: "Vous payez lorsque nous employons la personne. La conversation et le devis viennent d’abord. Le coût mensuel est confirmé avant votre engagement." },
      { q: "Comment vérifier un bulletin ?", a: "Chaque document émis peut être vérifié avec son code. Le contrôle public confirme que le document est valide. Il n’affiche ni le salaire ni les coordonnées bancaires." },
    ],
    ctaTitle: "Vous hésitez encore ?",
    ctaBody: "Envoyez le rôle. Nous répondrons avec le cadre et le coût.",
    ctaAction: "Nous contacter",
  },
  contact: {
    metaTitle: "Contact",
    kicker: "Contact",
    title: "Dites-nous qui vous voulez employer.",
    lede: "Nous répondons sous un jour ouvré. Le premier appel porte sur le rôle, le coût et notre capacité à employer la personne.",
    emailLabel: "E-mail",
    email: "thenovaworkforce@gmail.com",
    emailNote: "Vous préférez écrire directement ? Utilisez l’adresse. Le formulaire arrive dans la même boîte.",
    form: {
      name: "Votre nom",
      email: "E-mail professionnel",
      organisation: "Société",
      phone: "Téléphone",
      optional: "Facultatif",
      topic: "Sujet",
      topics: [
        { value: "eor", label: "Employer quelqu’un en Inde" },
        { value: "payroll", label: "Paie ou document" },
        { value: "careers", label: "Travailler avec le groupe Nova" },
        { value: "other", label: "Autre sujet" },
      ],
      message: "Message",
      messageHint: "Le rôle, le pays d’où vous opérez, et le salaire envisagé.",
      submit: "Envoyer",
      sending: "Envoi…",
      success: "Bien reçu. Nous répondrons à l’adresse indiquée.",
      error: "L’envoi a échoué. Écrivez-nous à l’adresse de cette page.",
      invalid: "Vérifiez les champs signalés et réessayez.",
    },
  },
  careers: {
    metaTitle: "Carrières",
    kicker: "Carrières",
    title: "Déjà employé chez nous ? Connectez-vous.",
    lede: "Les employés de Nova Workforce et de Nova Qore utilisent le portail employé pour les bulletins et documents. Nous ne publions pas d’offres sur ce site.",
    cards: [
      { title: "Employés", body: "Connectez-vous avec votre identifiant employé ou votre mobile enregistré.", action: "Connexion employé", href: "/login/employee" },
      { title: "Administrateurs et autres utilisateurs", body: "Les super admins, les responsables des opérations et les autres utilisateurs autorisés passent par le portail admin.", action: "Connexion admin", href: "/login/admin" },
      { title: "Vous voulez travailler avec le groupe ?", body: "Écrivez via le formulaire. Indiquez votre métier et votre lieu.", action: "Contact", href: "/contact" },
    ],
  },
  privacy: {
    metaTitle: "Confidentialité",
    kicker: "Confidentialité",
    title: "Comment ce site traite les informations personnelles.",
    lede: "Les pages publiques et le portail employé sont deux espaces, avec des données différentes.",
    sections: [
      { title: "Qui nous sommes", body: "Ce site est exploité pour le groupe Nova, soit Nova Workforce et Nova Qore. Les questions de confidentialité vont à thenovaworkforce@gmail.com." },
      { title: "Pages publiques", body: "Lire les pages publiques ne demande pas de compte. Nous ne vous demandons pas d’en créer un." },
      { title: "Formulaire de contact", body: "Si vous nous écrivez, nous recevons votre nom, votre e-mail, votre société, votre téléphone si vous l’avez donné, le sujet et le message. Nous nous en servons pour répondre. Nous ne les vendons pas." },
      { title: "Portail employés et admin", body: "Les bulletins, coordonnées bancaires et dossiers d’emploi ne sont accessibles qu’à l’employé concerné et aux opérateurs autorisés de sa société. La vérification publique confirme qu’un document est valide et n’affiche ni salaire ni données bancaires." },
      { title: "Durée de conservation d’un message", body: "Les messages de contact sont envoyés par e-mail à la boîte du groupe. Conservez une copie de ce dont vous avez besoin." },
      { title: "Nous écrire", body: "Pour une question sur vos informations, écrivez à thenovaworkforce@gmail.com depuis l’adresse que vous avez utilisée." },
    ],
  },
};
